SchoolStoreProject/schoolstoreproject/schoolstoreproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('storeapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SchoolStoreProject/schoolstoreproject/storeapp/urls.py
from django.urls import path,include
from.import views
app_name='storeapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('login/',views.login1,name='login'),
    path('register/',views.register1,name='register'),
    path('new/',views.new,name='new'),
    path('add/', views.person_create_view, name='add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('load-courses/', views.load_courses, name='load_courses'),  # AJAX
    path('new3/',views.new3,name='new3'),
    path('logout/',views.logout,name='logout')

]

SchoolStoreProject/schoolstoreproject/storeapp/models.py
from django.db import models

# Create your models here.
class logins(models.Model):
    username=models.CharField(max_length=250)
    password=models.CharField(max_length=250)

class register(models.Model):
    username = models.CharField(max_length=250)
    password = models.CharField(max_length=250)
    password1 = models.CharField(max_length=250)

class Department(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Course(models.Model):
    name=models.CharField(max_length=50)
    department=models.ForeignKey(Department, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
class Person(models.Model):
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

SchoolStoreProject/schoolstoreproject/storeapp/forms.py
from django import forms

from.models import Person,Department,Course


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        # if 'country' in self.data:
        #     try:
        #         country_id = int(self.data.get('country'))
        #         self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
        #     except (ValueError, TypeError):
        #         pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

SchoolStoreProject/schoolstoreproject/storeapp/views.py
from django.contrib import messages, auth
from django.http import HttpResponse
from .models import logins, register, Course, Person
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PersonCreationForm

# Create your views here.
def index(request):
    return render(request,'index.html')

def login1(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        s=logins(username=username,password=password)
        s.save()
        return redirect('/login')
    return render(request,'login.html')

def register1(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        password1=request.POST['password1']
        p=register(username=username,password=password,password1=password1)
        p.save()
        return redirect('/new')
    return render(request,'register.html')

def new(request):
    form=PersonCreationForm()
    if request.method == 'POST':
        return redirect('/add')
    return render(request,'new.html',{'form':form})

def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        return redirect('/new3')
    return render(request, 'form.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        form.save()
        return redirect('/')
    return render(request, 'form.html', {'form': form})

# AJAX
def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'course_options.html', {'courses': courses})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

def new3(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        return redirect('/')
    return render(request, 'new3.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('/')

SchoolStoreProject/schoolstoreproject/templates/course_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

SchoolStoreProject/schoolstoreproject/templates/form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Form</title>
    <link rel="stylesheet" href="{% static 'form1.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body class="wrapper">
<h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Form</h1>
<form method="post" id="form" data-courses-url="{% url 'storeapp:load_courses' %}">
    {% csrf_token %}

           <label>Name</label>
       &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="name" placeholder="name"><br><br>
        <label>DOB</label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="date" name="dob" placeholder="dob"><br><br>
            &nbsp;&nbsp;<label>Age</label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="number" name="age" placeholder="age"><br><br>
            <label>Address</label>
        &nbsp;&nbsp;&nbsp;<input type="text" name="address" placeholder="address"><br><br>
    <label>Gender:</label>
    &nbsp;&nbsp;&nbsp;<input type="radio" value="gender"   placeholder="gender">F
    <input type="radio" value="gender" placeholder="gender">M
    <br><br>
        <label>Email</label>
   &nbsp;&nbsp;&nbsp;&nbsp; <input type="email" name="email" placeholder="email"><br>
    {{ form.as_p }}<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button type="submit">Submit<a href="{% url 'storeapp:new3' %}"></a></button>
    <button><a href="{% url 'storeapp:logout' %}">Logout</a> </button>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#form").attr("data-courses-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_course").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

SchoolStoreProject/schoolstoreproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Education</title>
    <link rel="stylesheet" href="static/custom1.css">
<script src="https://kit.fontawesome.com/b0ec5853ee.js" crossorigin="anonymous"></script>
</head>
<body>
<div class="menu_bar">
        <h1 class="logo">School Store</h1>
    <ul>
        <li><a href="" class="active">Home</a></li>
        <li>
            <a href="">Department&nbsp;<i class="fa-solid fa-caret-down"></i></a>
        <div class="dropdown_menu">
            <ul>
            <li><a href="https://en.wikipedia.org/wiki/Computer_science">Computer Scienc</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Humanities">Humanities</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Science">Science</a></li>
            </ul>
        </div>
        </li>
        <li><a href="login">Login</a></li>
        <li><a href="register">Register</a></li>
        <li><a href="logout">Logout</a> </li>
    </ul>
</div>
<section>
    <img src="static/image_5.jpg" width="1500px;">
</section>
</body>
</html>

SchoolStoreProject/schoolstoreproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>Login</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body>
<div class="wrapper">
    <form action="" method="post">
        {% csrf_token %}
        <h1>Login</h1>
        <div class="input-box">
            <input type="text" name="username" placeholder="Username" required>
            <i class="bx bxs-user"></i>
        </div>
        <div class="input-box">
            <input type="password" name="password"   placeholder="Password" required>
            <i class="bx bxs-lock-alt"></i>
        </div>
        <div class="remember-forgot">
            <label><input type="checkbox">Remember me</label>
            <a href="#">Forget password?</a>
        </div>
        <button type="submit" class="btn">Login</button>
        <div class="register-link">
            <p>Don't have an account?&nbsp;&nbsp;<a
                    href="{% url 'storeapp:register' %}">Register</a></p>
        </div>
    </form>
</div>
</body>
</html>

SchoolStoreProject/schoolstoreproject/templates/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new</title>
    <link rel="stylesheet" href="{% static 'new2.css' %}">
</head>
<body>

<button><a href="{% url 'storeapp:add' %}">Click Here</a></button>
</body>
</html>

SchoolStoreProject/schoolstoreproject/templates/new3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'new3.css' %}">
</head>
<body>
<div class="container">

<div class="popup">
    <img src="{% static 'img6.jpg' %}">
    <h2>Thank You!</h2>
    <p>Your details has been successfully submitted.</p>
    <button ><a href="{% url 'storeapp:logout' %}">Ok</a></button>
</div>
</div>
</body>
</html>

SchoolStoreProject/schoolstoreproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'register.css' %}">
</head>
<body>
<div class="container">
    <div class="form-box">
        <form action="" name="Formfill" method="post">
            {% csrf_token %}
            <h2>Register</h2>
            <div class="input-box">
                <input type="text" name="username"  placeholder="Username" required>
            </div>
            <div class="input-box">
                <input type="password" name="password"  placeholder="Password" required>
            </div>
            <div class="input-box">
                <input type="password"  name="password1" placeholder="Confirm Password" required>
            </div>
            <div class="button">
                <button class="btn">Register</button>
                <a href="{% url 'storeapp:new' %}"></a>
            </div>
            <div class="group">
                <span><a href="{%url 'storeapp:login' %}">Login</a></span>
            </div>
        </form>
    </div>
</div>
</body>
</html>